// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package marginfi

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// DeactivateUtp is the `deactivateUtp` instruction.
type DeactivateUtp struct {
	UtpIndex *uint64

	// [0] = [WRITE] marginfiAccount
	//
	// [1] = [SIGNER] authority
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewDeactivateUtpInstructionBuilder creates a new `DeactivateUtp` instruction builder.
func NewDeactivateUtpInstructionBuilder() *DeactivateUtp {
	nd := &DeactivateUtp{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetUtpIndex sets the "utpIndex" parameter.
func (inst *DeactivateUtp) SetUtpIndex(utpIndex uint64) *DeactivateUtp {
	inst.UtpIndex = &utpIndex
	return inst
}

// SetMarginfiAccount sets the "marginfiAccount" account.
func (inst *DeactivateUtp) SetMarginfiAccount(marginfiAccount ag_solanago.PublicKey) *DeactivateUtp {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(marginfiAccount).WRITE()
	return inst
}

// GetMarginfiAccount gets the "marginfiAccount" account.
func (inst *DeactivateUtp) GetMarginfiAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAuthorityAccount sets the "authority" account.
func (inst *DeactivateUtp) SetAuthorityAccount(authority ag_solanago.PublicKey) *DeactivateUtp {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *DeactivateUtp) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst DeactivateUtp) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_DeactivateUtp,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst DeactivateUtp) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *DeactivateUtp) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.UtpIndex == nil {
			return errors.New("UtpIndex parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.MarginfiAccount is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.Authority is not set")
		}
	}
	return nil
}

func (inst *DeactivateUtp) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("DeactivateUtp")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("UtpIndex", *inst.UtpIndex))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta(" marginfi", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("authority", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj DeactivateUtp) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `UtpIndex` param:
	err = encoder.Encode(obj.UtpIndex)
	if err != nil {
		return err
	}
	return nil
}
func (obj *DeactivateUtp) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `UtpIndex`:
	err = decoder.Decode(&obj.UtpIndex)
	if err != nil {
		return err
	}
	return nil
}

// NewDeactivateUtpInstruction declares a new DeactivateUtp instruction with the provided parameters and accounts.
func NewDeactivateUtpInstruction(
	// Parameters:
	utpIndex uint64,
	// Accounts:
	marginfiAccount ag_solanago.PublicKey,
	authority ag_solanago.PublicKey) *DeactivateUtp {
	return NewDeactivateUtpInstructionBuilder().
		SetUtpIndex(utpIndex).
		SetMarginfiAccount(marginfiAccount).
		SetAuthorityAccount(authority)
}
