// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package marginfi

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UtpMangoWithdraw is the `utpMangoWithdraw` instruction.
type UtpMangoWithdraw struct {
	Amount *uint64

	// [0] = [WRITE] marginfiAccount
	//
	// [1] = [WRITE] marginfiGroup
	//
	// [2] = [SIGNER] signer
	//
	// [3] = [WRITE] marginCollateralVault
	//
	// [4] = [] mangoAuthority
	//
	// [5] = [WRITE] mangoAccount
	//
	// [6] = [] mangoProgram
	//
	// [7] = [] mangoGroup
	//
	// [8] = [] mangoCache
	//
	// [9] = [] mangoRootBank
	//
	// [10] = [WRITE] mangoNodeBank
	//
	// [11] = [WRITE] mangoVault
	//
	// [12] = [] mangoVaultAuthority
	//
	// [13] = [] tokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUtpMangoWithdrawInstructionBuilder creates a new `UtpMangoWithdraw` instruction builder.
func NewUtpMangoWithdrawInstructionBuilder() *UtpMangoWithdraw {
	nd := &UtpMangoWithdraw{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 14),
	}
	return nd
}

// SetAmount sets the "amount" parameter.
func (inst *UtpMangoWithdraw) SetAmount(amount uint64) *UtpMangoWithdraw {
	inst.Amount = &amount
	return inst
}

// SetMarginfiAccount sets the "marginfiAccount" account.
func (inst *UtpMangoWithdraw) SetMarginfiAccount(marginfiAccount ag_solanago.PublicKey) *UtpMangoWithdraw {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(marginfiAccount).WRITE()
	return inst
}

// GetMarginfiAccount gets the "marginfiAccount" account.
func (inst *UtpMangoWithdraw) GetMarginfiAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetMarginfiGroupAccount sets the "marginfiGroup" account.
func (inst *UtpMangoWithdraw) SetMarginfiGroupAccount(marginfiGroup ag_solanago.PublicKey) *UtpMangoWithdraw {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(marginfiGroup).WRITE()
	return inst
}

// GetMarginfiGroupAccount gets the "marginfiGroup" account.
func (inst *UtpMangoWithdraw) GetMarginfiGroupAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSignerAccount sets the "signer" account.
func (inst *UtpMangoWithdraw) SetSignerAccount(signer ag_solanago.PublicKey) *UtpMangoWithdraw {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(signer).SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *UtpMangoWithdraw) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetMarginCollateralVaultAccount sets the "marginCollateralVault" account.
func (inst *UtpMangoWithdraw) SetMarginCollateralVaultAccount(marginCollateralVault ag_solanago.PublicKey) *UtpMangoWithdraw {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(marginCollateralVault).WRITE()
	return inst
}

// GetMarginCollateralVaultAccount gets the "marginCollateralVault" account.
func (inst *UtpMangoWithdraw) GetMarginCollateralVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetMangoAuthorityAccount sets the "mangoAuthority" account.
func (inst *UtpMangoWithdraw) SetMangoAuthorityAccount(mangoAuthority ag_solanago.PublicKey) *UtpMangoWithdraw {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(mangoAuthority)
	return inst
}

// GetMangoAuthorityAccount gets the "mangoAuthority" account.
func (inst *UtpMangoWithdraw) GetMangoAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetMangoAccount sets the "mangoAccount" account.
func (inst *UtpMangoWithdraw) SetMangoAccount(mangoAccount ag_solanago.PublicKey) *UtpMangoWithdraw {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(mangoAccount).WRITE()
	return inst
}

// GetMangoAccount gets the "mangoAccount" account.
func (inst *UtpMangoWithdraw) GetMangoAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetMangoProgramAccount sets the "mangoProgram" account.
func (inst *UtpMangoWithdraw) SetMangoProgramAccount(mangoProgram ag_solanago.PublicKey) *UtpMangoWithdraw {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(mangoProgram)
	return inst
}

// GetMangoProgramAccount gets the "mangoProgram" account.
func (inst *UtpMangoWithdraw) GetMangoProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetMangoGroupAccount sets the "mangoGroup" account.
func (inst *UtpMangoWithdraw) SetMangoGroupAccount(mangoGroup ag_solanago.PublicKey) *UtpMangoWithdraw {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(mangoGroup)
	return inst
}

// GetMangoGroupAccount gets the "mangoGroup" account.
func (inst *UtpMangoWithdraw) GetMangoGroupAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetMangoCacheAccount sets the "mangoCache" account.
func (inst *UtpMangoWithdraw) SetMangoCacheAccount(mangoCache ag_solanago.PublicKey) *UtpMangoWithdraw {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(mangoCache)
	return inst
}

// GetMangoCacheAccount gets the "mangoCache" account.
func (inst *UtpMangoWithdraw) GetMangoCacheAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetMangoRootBankAccount sets the "mangoRootBank" account.
func (inst *UtpMangoWithdraw) SetMangoRootBankAccount(mangoRootBank ag_solanago.PublicKey) *UtpMangoWithdraw {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(mangoRootBank)
	return inst
}

// GetMangoRootBankAccount gets the "mangoRootBank" account.
func (inst *UtpMangoWithdraw) GetMangoRootBankAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetMangoNodeBankAccount sets the "mangoNodeBank" account.
func (inst *UtpMangoWithdraw) SetMangoNodeBankAccount(mangoNodeBank ag_solanago.PublicKey) *UtpMangoWithdraw {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(mangoNodeBank).WRITE()
	return inst
}

// GetMangoNodeBankAccount gets the "mangoNodeBank" account.
func (inst *UtpMangoWithdraw) GetMangoNodeBankAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetMangoVaultAccount sets the "mangoVault" account.
func (inst *UtpMangoWithdraw) SetMangoVaultAccount(mangoVault ag_solanago.PublicKey) *UtpMangoWithdraw {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(mangoVault).WRITE()
	return inst
}

// GetMangoVaultAccount gets the "mangoVault" account.
func (inst *UtpMangoWithdraw) GetMangoVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetMangoVaultAuthorityAccount sets the "mangoVaultAuthority" account.
func (inst *UtpMangoWithdraw) SetMangoVaultAuthorityAccount(mangoVaultAuthority ag_solanago.PublicKey) *UtpMangoWithdraw {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(mangoVaultAuthority)
	return inst
}

// GetMangoVaultAuthorityAccount gets the "mangoVaultAuthority" account.
func (inst *UtpMangoWithdraw) GetMangoVaultAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *UtpMangoWithdraw) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *UtpMangoWithdraw {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *UtpMangoWithdraw) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

func (inst UtpMangoWithdraw) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UtpMangoWithdraw,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UtpMangoWithdraw) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UtpMangoWithdraw) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Amount == nil {
			return errors.New("Amount parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.MarginfiAccount is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.MarginfiGroup is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Signer is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.MarginCollateralVault is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.MangoAuthority is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.MangoAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.MangoProgram is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.MangoGroup is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.MangoCache is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.MangoRootBank is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.MangoNodeBank is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.MangoVault is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.MangoVaultAuthority is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
	}
	return nil
}

func (inst *UtpMangoWithdraw) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UtpMangoWithdraw")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Amount", *inst.Amount))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=14]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("             marginfi", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("        marginfiGroup", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("               signer", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("marginCollateralVault", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("       mangoAuthority", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("                mango", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("         mangoProgram", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("           mangoGroup", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("           mangoCache", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("        mangoRootBank", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("        mangoNodeBank", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("           mangoVault", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("  mangoVaultAuthority", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("         tokenProgram", inst.AccountMetaSlice.Get(13)))
					})
				})
		})
}

func (obj UtpMangoWithdraw) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Amount` param:
	err = encoder.Encode(obj.Amount)
	if err != nil {
		return err
	}
	return nil
}
func (obj *UtpMangoWithdraw) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Amount`:
	err = decoder.Decode(&obj.Amount)
	if err != nil {
		return err
	}
	return nil
}

// NewUtpMangoWithdrawInstruction declares a new UtpMangoWithdraw instruction with the provided parameters and accounts.
func NewUtpMangoWithdrawInstruction(
	// Parameters:
	amount uint64,
	// Accounts:
	marginfiAccount ag_solanago.PublicKey,
	marginfiGroup ag_solanago.PublicKey,
	signer ag_solanago.PublicKey,
	marginCollateralVault ag_solanago.PublicKey,
	mangoAuthority ag_solanago.PublicKey,
	mangoAccount ag_solanago.PublicKey,
	mangoProgram ag_solanago.PublicKey,
	mangoGroup ag_solanago.PublicKey,
	mangoCache ag_solanago.PublicKey,
	mangoRootBank ag_solanago.PublicKey,
	mangoNodeBank ag_solanago.PublicKey,
	mangoVault ag_solanago.PublicKey,
	mangoVaultAuthority ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *UtpMangoWithdraw {
	return NewUtpMangoWithdrawInstructionBuilder().
		SetAmount(amount).
		SetMarginfiAccount(marginfiAccount).
		SetMarginfiGroupAccount(marginfiGroup).
		SetSignerAccount(signer).
		SetMarginCollateralVaultAccount(marginCollateralVault).
		SetMangoAuthorityAccount(mangoAuthority).
		SetMangoAccount(mangoAccount).
		SetMangoProgramAccount(mangoProgram).
		SetMangoGroupAccount(mangoGroup).
		SetMangoCacheAccount(mangoCache).
		SetMangoRootBankAccount(mangoRootBank).
		SetMangoNodeBankAccount(mangoNodeBank).
		SetMangoVaultAccount(mangoVault).
		SetMangoVaultAuthorityAccount(mangoVaultAuthority).
		SetTokenProgramAccount(tokenProgram)
}
