// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package marginfi

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UtpZoPlacePerpOrder is the `utpZoPlacePerpOrder` instruction.
type UtpZoPlacePerpOrder struct {
	Args *UtpZoPlacePerpOrderIxArgs

	// ····· header: [0] = [] marginfiAccount
	//
	// ············· [1] = [] marginfiGroup
	//
	// ············· [2] = [WRITE, SIGNER] signer
	//
	// ············· [3] = [] utpAuthority
	//
	// [4] = [] zoProgram
	//
	// [5] = [] state
	//
	// [6] = [WRITE] stateSigner
	//
	// [7] = [WRITE] cache
	//
	// [8] = [WRITE] margin
	//
	// [9] = [WRITE] control
	//
	// [10] = [WRITE] openOrders
	//
	// [11] = [WRITE] dexMarket
	//
	// [12] = [WRITE] reqQ
	//
	// [13] = [WRITE] eventQ
	//
	// [14] = [WRITE] marketBids
	//
	// [15] = [WRITE] marketAsks
	//
	// [16] = [] dexProgram
	//
	// [17] = [] rent
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUtpZoPlacePerpOrderInstructionBuilder creates a new `UtpZoPlacePerpOrder` instruction builder.
func NewUtpZoPlacePerpOrderInstructionBuilder() *UtpZoPlacePerpOrder {
	nd := &UtpZoPlacePerpOrder{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 18),
	}
	return nd
}

// SetArgs sets the "args" parameter.
func (inst *UtpZoPlacePerpOrder) SetArgs(args UtpZoPlacePerpOrderIxArgs) *UtpZoPlacePerpOrder {
	inst.Args = &args
	return inst
}

type UtpZoPlacePerpOrderHeaderAccountsBuilder struct {
	ag_solanago.AccountMetaSlice `bin:"-"`
}

func NewUtpZoPlacePerpOrderHeaderAccountsBuilder() *UtpZoPlacePerpOrderHeaderAccountsBuilder {
	return &UtpZoPlacePerpOrderHeaderAccountsBuilder{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
}

func (inst *UtpZoPlacePerpOrder) SetHeaderAccountsFromBuilder(utpZoPlacePerpOrderHeaderAccountsBuilder *UtpZoPlacePerpOrderHeaderAccountsBuilder) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[0] = utpZoPlacePerpOrderHeaderAccountsBuilder.GetMarginfiAccount()
	inst.AccountMetaSlice[1] = utpZoPlacePerpOrderHeaderAccountsBuilder.GetMarginfiGroupAccount()
	inst.AccountMetaSlice[2] = utpZoPlacePerpOrderHeaderAccountsBuilder.GetSignerAccount()
	inst.AccountMetaSlice[3] = utpZoPlacePerpOrderHeaderAccountsBuilder.GetUtpAuthorityAccount()
	return inst
}

// SetMarginfiAccount sets the "marginfiAccount" account.
func (inst *UtpZoPlacePerpOrderHeaderAccountsBuilder) SetMarginfiAccount(marginfiAccount ag_solanago.PublicKey) *UtpZoPlacePerpOrderHeaderAccountsBuilder {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(marginfiAccount)
	return inst
}

// GetMarginfiAccount gets the "marginfiAccount" account.
func (inst *UtpZoPlacePerpOrderHeaderAccountsBuilder) GetMarginfiAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetMarginfiGroupAccount sets the "marginfiGroup" account.
func (inst *UtpZoPlacePerpOrderHeaderAccountsBuilder) SetMarginfiGroupAccount(marginfiGroup ag_solanago.PublicKey) *UtpZoPlacePerpOrderHeaderAccountsBuilder {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(marginfiGroup)
	return inst
}

// GetMarginfiGroupAccount gets the "marginfiGroup" account.
func (inst *UtpZoPlacePerpOrderHeaderAccountsBuilder) GetMarginfiGroupAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSignerAccount sets the "signer" account.
func (inst *UtpZoPlacePerpOrderHeaderAccountsBuilder) SetSignerAccount(signer ag_solanago.PublicKey) *UtpZoPlacePerpOrderHeaderAccountsBuilder {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *UtpZoPlacePerpOrderHeaderAccountsBuilder) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetUtpAuthorityAccount sets the "utpAuthority" account.
func (inst *UtpZoPlacePerpOrderHeaderAccountsBuilder) SetUtpAuthorityAccount(utpAuthority ag_solanago.PublicKey) *UtpZoPlacePerpOrderHeaderAccountsBuilder {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(utpAuthority)
	return inst
}

// GetUtpAuthorityAccount gets the "utpAuthority" account.
func (inst *UtpZoPlacePerpOrderHeaderAccountsBuilder) GetUtpAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetZoProgramAccount sets the "zoProgram" account.
func (inst *UtpZoPlacePerpOrder) SetZoProgramAccount(zoProgram ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(zoProgram)
	return inst
}

// GetZoProgramAccount gets the "zoProgram" account.
func (inst *UtpZoPlacePerpOrder) GetZoProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetStateAccount sets the "state" account.
func (inst *UtpZoPlacePerpOrder) SetStateAccount(state ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(state)
	return inst
}

// GetStateAccount gets the "state" account.
func (inst *UtpZoPlacePerpOrder) GetStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetStateSignerAccount sets the "stateSigner" account.
func (inst *UtpZoPlacePerpOrder) SetStateSignerAccount(stateSigner ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(stateSigner).WRITE()
	return inst
}

// GetStateSignerAccount gets the "stateSigner" account.
func (inst *UtpZoPlacePerpOrder) GetStateSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetCacheAccount sets the "cache" account.
func (inst *UtpZoPlacePerpOrder) SetCacheAccount(cache ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(cache).WRITE()
	return inst
}

// GetCacheAccount gets the "cache" account.
func (inst *UtpZoPlacePerpOrder) GetCacheAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetMarginAccount sets the "margin" account.
func (inst *UtpZoPlacePerpOrder) SetMarginAccount(margin ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(margin).WRITE()
	return inst
}

// GetMarginAccount gets the "margin" account.
func (inst *UtpZoPlacePerpOrder) GetMarginAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetControlAccount sets the "control" account.
func (inst *UtpZoPlacePerpOrder) SetControlAccount(control ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(control).WRITE()
	return inst
}

// GetControlAccount gets the "control" account.
func (inst *UtpZoPlacePerpOrder) GetControlAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetOpenOrdersAccount sets the "openOrders" account.
func (inst *UtpZoPlacePerpOrder) SetOpenOrdersAccount(openOrders ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(openOrders).WRITE()
	return inst
}

// GetOpenOrdersAccount gets the "openOrders" account.
func (inst *UtpZoPlacePerpOrder) GetOpenOrdersAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetDexMarketAccount sets the "dexMarket" account.
func (inst *UtpZoPlacePerpOrder) SetDexMarketAccount(dexMarket ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(dexMarket).WRITE()
	return inst
}

// GetDexMarketAccount gets the "dexMarket" account.
func (inst *UtpZoPlacePerpOrder) GetDexMarketAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetReqQAccount sets the "reqQ" account.
func (inst *UtpZoPlacePerpOrder) SetReqQAccount(reqQ ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(reqQ).WRITE()
	return inst
}

// GetReqQAccount gets the "reqQ" account.
func (inst *UtpZoPlacePerpOrder) GetReqQAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetEventQAccount sets the "eventQ" account.
func (inst *UtpZoPlacePerpOrder) SetEventQAccount(eventQ ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(eventQ).WRITE()
	return inst
}

// GetEventQAccount gets the "eventQ" account.
func (inst *UtpZoPlacePerpOrder) GetEventQAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

// SetMarketBidsAccount sets the "marketBids" account.
func (inst *UtpZoPlacePerpOrder) SetMarketBidsAccount(marketBids ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[14] = ag_solanago.Meta(marketBids).WRITE()
	return inst
}

// GetMarketBidsAccount gets the "marketBids" account.
func (inst *UtpZoPlacePerpOrder) GetMarketBidsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(14)
}

// SetMarketAsksAccount sets the "marketAsks" account.
func (inst *UtpZoPlacePerpOrder) SetMarketAsksAccount(marketAsks ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[15] = ag_solanago.Meta(marketAsks).WRITE()
	return inst
}

// GetMarketAsksAccount gets the "marketAsks" account.
func (inst *UtpZoPlacePerpOrder) GetMarketAsksAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(15)
}

// SetDexProgramAccount sets the "dexProgram" account.
func (inst *UtpZoPlacePerpOrder) SetDexProgramAccount(dexProgram ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[16] = ag_solanago.Meta(dexProgram)
	return inst
}

// GetDexProgramAccount gets the "dexProgram" account.
func (inst *UtpZoPlacePerpOrder) GetDexProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(16)
}

// SetRentAccount sets the "rent" account.
func (inst *UtpZoPlacePerpOrder) SetRentAccount(rent ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	inst.AccountMetaSlice[17] = ag_solanago.Meta(rent)
	return inst
}

// GetRentAccount gets the "rent" account.
func (inst *UtpZoPlacePerpOrder) GetRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(17)
}

func (inst UtpZoPlacePerpOrder) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UtpZoPlacePerpOrder,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UtpZoPlacePerpOrder) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UtpZoPlacePerpOrder) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Args == nil {
			return errors.New("Args parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.HeaderMarginfiAccount is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.HeaderMarginfiGroup is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.HeaderSigner is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.HeaderUtpAuthority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.ZoProgram is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.State is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.StateSigner is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Cache is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.Margin is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.Control is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.OpenOrders is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.DexMarket is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.ReqQ is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.EventQ is not set")
		}
		if inst.AccountMetaSlice[14] == nil {
			return errors.New("accounts.MarketBids is not set")
		}
		if inst.AccountMetaSlice[15] == nil {
			return errors.New("accounts.MarketAsks is not set")
		}
		if inst.AccountMetaSlice[16] == nil {
			return errors.New("accounts.DexProgram is not set")
		}
		if inst.AccountMetaSlice[17] == nil {
			return errors.New("accounts.Rent is not set")
		}
	}
	return nil
}

func (inst *UtpZoPlacePerpOrder) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UtpZoPlacePerpOrder")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Args", *inst.Args))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=18]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("     header/marginfi", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("header/marginfiGroup", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       header/signer", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta(" header/utpAuthority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("           zoProgram", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("               state", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("         stateSigner", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("               cache", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("              margin", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("             control", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("          openOrders", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("           dexMarket", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("                reqQ", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("              eventQ", inst.AccountMetaSlice.Get(13)))
						accountsBranch.Child(ag_format.Meta("          marketBids", inst.AccountMetaSlice.Get(14)))
						accountsBranch.Child(ag_format.Meta("          marketAsks", inst.AccountMetaSlice.Get(15)))
						accountsBranch.Child(ag_format.Meta("          dexProgram", inst.AccountMetaSlice.Get(16)))
						accountsBranch.Child(ag_format.Meta("                rent", inst.AccountMetaSlice.Get(17)))
					})
				})
		})
}

func (obj UtpZoPlacePerpOrder) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Args` param:
	err = encoder.Encode(obj.Args)
	if err != nil {
		return err
	}
	return nil
}
func (obj *UtpZoPlacePerpOrder) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Args`:
	err = decoder.Decode(&obj.Args)
	if err != nil {
		return err
	}
	return nil
}

// NewUtpZoPlacePerpOrderInstruction declares a new UtpZoPlacePerpOrder instruction with the provided parameters and accounts.
func NewUtpZoPlacePerpOrderInstruction(
	// Parameters:
	args UtpZoPlacePerpOrderIxArgs,
	// Accounts:
	headerMarginfiAccount ag_solanago.PublicKey,
	headerMarginfiGroup ag_solanago.PublicKey,
	headerSigner ag_solanago.PublicKey,
	headerUtpAuthority ag_solanago.PublicKey,
	zoProgram ag_solanago.PublicKey,
	state ag_solanago.PublicKey,
	stateSigner ag_solanago.PublicKey,
	cache ag_solanago.PublicKey,
	margin ag_solanago.PublicKey,
	control ag_solanago.PublicKey,
	openOrders ag_solanago.PublicKey,
	dexMarket ag_solanago.PublicKey,
	reqQ ag_solanago.PublicKey,
	eventQ ag_solanago.PublicKey,
	marketBids ag_solanago.PublicKey,
	marketAsks ag_solanago.PublicKey,
	dexProgram ag_solanago.PublicKey,
	rent ag_solanago.PublicKey) *UtpZoPlacePerpOrder {
	return NewUtpZoPlacePerpOrderInstructionBuilder().
		SetArgs(args).
		SetHeaderAccountsFromBuilder(
			NewUtpZoPlacePerpOrderHeaderAccountsBuilder().
				SetMarginfiAccount(headerMarginfiAccount).
				SetMarginfiGroupAccount(headerMarginfiGroup).
				SetSignerAccount(headerSigner).
				SetUtpAuthorityAccount(headerUtpAuthority),
		).
		SetZoProgramAccount(zoProgram).
		SetStateAccount(state).
		SetStateSignerAccount(stateSigner).
		SetCacheAccount(cache).
		SetMarginAccount(margin).
		SetControlAccount(control).
		SetOpenOrdersAccount(openOrders).
		SetDexMarketAccount(dexMarket).
		SetReqQAccount(reqQ).
		SetEventQAccount(eventQ).
		SetMarketBidsAccount(marketBids).
		SetMarketAsksAccount(marketAsks).
		SetDexProgramAccount(dexProgram).
		SetRentAccount(rent)
}
