// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package marginfi

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// UtpZoCancelPerpOrder is the `utpZoCancelPerpOrder` instruction.
type UtpZoCancelPerpOrder struct {
	OrderId  *ag_binary.Uint128 `bin:"optional"`
	IsLong   *bool              `bin:"optional"`
	ClientId *uint64            `bin:"optional"`

	// ····· header: [0] = [] marginfiAccount
	//
	// ············· [1] = [] marginfiGroup
	//
	// ············· [2] = [WRITE, SIGNER] signer
	//
	// ············· [3] = [] utpAuthority
	//
	// [4] = [] zoProgram
	//
	// [5] = [] state
	//
	// [6] = [WRITE] cache
	//
	// [7] = [WRITE] margin
	//
	// [8] = [WRITE] control
	//
	// [9] = [WRITE] openOrders
	//
	// [10] = [WRITE] dexMarket
	//
	// [11] = [WRITE] marketBids
	//
	// [12] = [WRITE] marketAsks
	//
	// [13] = [WRITE] eventQ
	//
	// [14] = [] dexProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUtpZoCancelPerpOrderInstructionBuilder creates a new `UtpZoCancelPerpOrder` instruction builder.
func NewUtpZoCancelPerpOrderInstructionBuilder() *UtpZoCancelPerpOrder {
	nd := &UtpZoCancelPerpOrder{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 15),
	}
	return nd
}

// SetOrderId sets the "orderId" parameter.
func (inst *UtpZoCancelPerpOrder) SetOrderId(orderId ag_binary.Uint128) *UtpZoCancelPerpOrder {
	inst.OrderId = &orderId
	return inst
}

// SetIsLong sets the "isLong" parameter.
func (inst *UtpZoCancelPerpOrder) SetIsLong(isLong bool) *UtpZoCancelPerpOrder {
	inst.IsLong = &isLong
	return inst
}

// SetClientId sets the "clientId" parameter.
func (inst *UtpZoCancelPerpOrder) SetClientId(clientId uint64) *UtpZoCancelPerpOrder {
	inst.ClientId = &clientId
	return inst
}

type UtpZoCancelPerpOrderHeaderAccountsBuilder struct {
	ag_solanago.AccountMetaSlice `bin:"-"`
}

func NewUtpZoCancelPerpOrderHeaderAccountsBuilder() *UtpZoCancelPerpOrderHeaderAccountsBuilder {
	return &UtpZoCancelPerpOrderHeaderAccountsBuilder{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
}

func (inst *UtpZoCancelPerpOrder) SetHeaderAccountsFromBuilder(utpZoCancelPerpOrderHeaderAccountsBuilder *UtpZoCancelPerpOrderHeaderAccountsBuilder) *UtpZoCancelPerpOrder {
	inst.AccountMetaSlice[0] = utpZoCancelPerpOrderHeaderAccountsBuilder.GetMarginfiAccount()
	inst.AccountMetaSlice[1] = utpZoCancelPerpOrderHeaderAccountsBuilder.GetMarginfiGroupAccount()
	inst.AccountMetaSlice[2] = utpZoCancelPerpOrderHeaderAccountsBuilder.GetSignerAccount()
	inst.AccountMetaSlice[3] = utpZoCancelPerpOrderHeaderAccountsBuilder.GetUtpAuthorityAccount()
	return inst
}

// SetMarginfiAccount sets the "marginfiAccount" account.
func (inst *UtpZoCancelPerpOrderHeaderAccountsBuilder) SetMarginfiAccount(marginfiAccount ag_solanago.PublicKey) *UtpZoCancelPerpOrderHeaderAccountsBuilder {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(marginfiAccount)
	return inst
}

// GetMarginfiAccount gets the "marginfiAccount" account.
func (inst *UtpZoCancelPerpOrderHeaderAccountsBuilder) GetMarginfiAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetMarginfiGroupAccount sets the "marginfiGroup" account.
func (inst *UtpZoCancelPerpOrderHeaderAccountsBuilder) SetMarginfiGroupAccount(marginfiGroup ag_solanago.PublicKey) *UtpZoCancelPerpOrderHeaderAccountsBuilder {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(marginfiGroup)
	return inst
}

// GetMarginfiGroupAccount gets the "marginfiGroup" account.
func (inst *UtpZoCancelPerpOrderHeaderAccountsBuilder) GetMarginfiGroupAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSignerAccount sets the "signer" account.
func (inst *UtpZoCancelPerpOrderHeaderAccountsBuilder) SetSignerAccount(signer ag_solanago.PublicKey) *UtpZoCancelPerpOrderHeaderAccountsBuilder {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(signer).WRITE().SIGNER()
	return inst
}

// GetSignerAccount gets the "signer" account.
func (inst *UtpZoCancelPerpOrderHeaderAccountsBuilder) GetSignerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetUtpAuthorityAccount sets the "utpAuthority" account.
func (inst *UtpZoCancelPerpOrderHeaderAccountsBuilder) SetUtpAuthorityAccount(utpAuthority ag_solanago.PublicKey) *UtpZoCancelPerpOrderHeaderAccountsBuilder {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(utpAuthority)
	return inst
}

// GetUtpAuthorityAccount gets the "utpAuthority" account.
func (inst *UtpZoCancelPerpOrderHeaderAccountsBuilder) GetUtpAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetZoProgramAccount sets the "zoProgram" account.
func (inst *UtpZoCancelPerpOrder) SetZoProgramAccount(zoProgram ag_solanago.PublicKey) *UtpZoCancelPerpOrder {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(zoProgram)
	return inst
}

// GetZoProgramAccount gets the "zoProgram" account.
func (inst *UtpZoCancelPerpOrder) GetZoProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetStateAccount sets the "state" account.
func (inst *UtpZoCancelPerpOrder) SetStateAccount(state ag_solanago.PublicKey) *UtpZoCancelPerpOrder {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(state)
	return inst
}

// GetStateAccount gets the "state" account.
func (inst *UtpZoCancelPerpOrder) GetStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetCacheAccount sets the "cache" account.
func (inst *UtpZoCancelPerpOrder) SetCacheAccount(cache ag_solanago.PublicKey) *UtpZoCancelPerpOrder {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(cache).WRITE()
	return inst
}

// GetCacheAccount gets the "cache" account.
func (inst *UtpZoCancelPerpOrder) GetCacheAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetMarginAccount sets the "margin" account.
func (inst *UtpZoCancelPerpOrder) SetMarginAccount(margin ag_solanago.PublicKey) *UtpZoCancelPerpOrder {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(margin).WRITE()
	return inst
}

// GetMarginAccount gets the "margin" account.
func (inst *UtpZoCancelPerpOrder) GetMarginAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetControlAccount sets the "control" account.
func (inst *UtpZoCancelPerpOrder) SetControlAccount(control ag_solanago.PublicKey) *UtpZoCancelPerpOrder {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(control).WRITE()
	return inst
}

// GetControlAccount gets the "control" account.
func (inst *UtpZoCancelPerpOrder) GetControlAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetOpenOrdersAccount sets the "openOrders" account.
func (inst *UtpZoCancelPerpOrder) SetOpenOrdersAccount(openOrders ag_solanago.PublicKey) *UtpZoCancelPerpOrder {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(openOrders).WRITE()
	return inst
}

// GetOpenOrdersAccount gets the "openOrders" account.
func (inst *UtpZoCancelPerpOrder) GetOpenOrdersAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetDexMarketAccount sets the "dexMarket" account.
func (inst *UtpZoCancelPerpOrder) SetDexMarketAccount(dexMarket ag_solanago.PublicKey) *UtpZoCancelPerpOrder {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(dexMarket).WRITE()
	return inst
}

// GetDexMarketAccount gets the "dexMarket" account.
func (inst *UtpZoCancelPerpOrder) GetDexMarketAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetMarketBidsAccount sets the "marketBids" account.
func (inst *UtpZoCancelPerpOrder) SetMarketBidsAccount(marketBids ag_solanago.PublicKey) *UtpZoCancelPerpOrder {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(marketBids).WRITE()
	return inst
}

// GetMarketBidsAccount gets the "marketBids" account.
func (inst *UtpZoCancelPerpOrder) GetMarketBidsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetMarketAsksAccount sets the "marketAsks" account.
func (inst *UtpZoCancelPerpOrder) SetMarketAsksAccount(marketAsks ag_solanago.PublicKey) *UtpZoCancelPerpOrder {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(marketAsks).WRITE()
	return inst
}

// GetMarketAsksAccount gets the "marketAsks" account.
func (inst *UtpZoCancelPerpOrder) GetMarketAsksAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetEventQAccount sets the "eventQ" account.
func (inst *UtpZoCancelPerpOrder) SetEventQAccount(eventQ ag_solanago.PublicKey) *UtpZoCancelPerpOrder {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(eventQ).WRITE()
	return inst
}

// GetEventQAccount gets the "eventQ" account.
func (inst *UtpZoCancelPerpOrder) GetEventQAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

// SetDexProgramAccount sets the "dexProgram" account.
func (inst *UtpZoCancelPerpOrder) SetDexProgramAccount(dexProgram ag_solanago.PublicKey) *UtpZoCancelPerpOrder {
	inst.AccountMetaSlice[14] = ag_solanago.Meta(dexProgram)
	return inst
}

// GetDexProgramAccount gets the "dexProgram" account.
func (inst *UtpZoCancelPerpOrder) GetDexProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(14)
}

func (inst UtpZoCancelPerpOrder) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UtpZoCancelPerpOrder,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UtpZoCancelPerpOrder) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UtpZoCancelPerpOrder) Validate() error {
	// Check whether all (required) parameters are set:
	{
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.HeaderMarginfiAccount is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.HeaderMarginfiGroup is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.HeaderSigner is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.HeaderUtpAuthority is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.ZoProgram is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.State is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.Cache is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.Margin is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.Control is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.OpenOrders is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.DexMarket is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.MarketBids is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.MarketAsks is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.EventQ is not set")
		}
		if inst.AccountMetaSlice[14] == nil {
			return errors.New("accounts.DexProgram is not set")
		}
	}
	return nil
}

func (inst *UtpZoCancelPerpOrder) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UtpZoCancelPerpOrder")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=3]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param(" OrderId (OPT)", inst.OrderId))
						paramsBranch.Child(ag_format.Param("  IsLong (OPT)", inst.IsLong))
						paramsBranch.Child(ag_format.Param("ClientId (OPT)", inst.ClientId))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=15]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("     header/marginfi", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("header/marginfiGroup", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("       header/signer", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta(" header/utpAuthority", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("           zoProgram", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("               state", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("               cache", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("              margin", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("             control", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("          openOrders", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("           dexMarket", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("          marketBids", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("          marketAsks", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("              eventQ", inst.AccountMetaSlice.Get(13)))
						accountsBranch.Child(ag_format.Meta("          dexProgram", inst.AccountMetaSlice.Get(14)))
					})
				})
		})
}

func (obj UtpZoCancelPerpOrder) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `OrderId` param (optional):
	{
		if obj.OrderId == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.OrderId)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `IsLong` param (optional):
	{
		if obj.IsLong == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.IsLong)
			if err != nil {
				return err
			}
		}
	}
	// Serialize `ClientId` param (optional):
	{
		if obj.ClientId == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.ClientId)
			if err != nil {
				return err
			}
		}
	}
	return nil
}
func (obj *UtpZoCancelPerpOrder) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `OrderId` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.OrderId)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `IsLong` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.IsLong)
			if err != nil {
				return err
			}
		}
	}
	// Deserialize `ClientId` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.ClientId)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// NewUtpZoCancelPerpOrderInstruction declares a new UtpZoCancelPerpOrder instruction with the provided parameters and accounts.
func NewUtpZoCancelPerpOrderInstruction(
	// Parameters:
	orderId ag_binary.Uint128,
	isLong bool,
	clientId uint64,
	// Accounts:
	headerMarginfiAccount ag_solanago.PublicKey,
	headerMarginfiGroup ag_solanago.PublicKey,
	headerSigner ag_solanago.PublicKey,
	headerUtpAuthority ag_solanago.PublicKey,
	zoProgram ag_solanago.PublicKey,
	state ag_solanago.PublicKey,
	cache ag_solanago.PublicKey,
	margin ag_solanago.PublicKey,
	control ag_solanago.PublicKey,
	openOrders ag_solanago.PublicKey,
	dexMarket ag_solanago.PublicKey,
	marketBids ag_solanago.PublicKey,
	marketAsks ag_solanago.PublicKey,
	eventQ ag_solanago.PublicKey,
	dexProgram ag_solanago.PublicKey) *UtpZoCancelPerpOrder {
	return NewUtpZoCancelPerpOrderInstructionBuilder().
		SetOrderId(orderId).
		SetIsLong(isLong).
		SetClientId(clientId).
		SetHeaderAccountsFromBuilder(
			NewUtpZoCancelPerpOrderHeaderAccountsBuilder().
				SetMarginfiAccount(headerMarginfiAccount).
				SetMarginfiGroupAccount(headerMarginfiGroup).
				SetSignerAccount(headerSigner).
				SetUtpAuthorityAccount(headerUtpAuthority),
		).
		SetZoProgramAccount(zoProgram).
		SetStateAccount(state).
		SetCacheAccount(cache).
		SetMarginAccount(margin).
		SetControlAccount(control).
		SetOpenOrdersAccount(openOrders).
		SetDexMarketAccount(dexMarket).
		SetMarketBidsAccount(marketBids).
		SetMarketAsksAccount(marketAsks).
		SetEventQAccount(eventQ).
		SetDexProgramAccount(dexProgram)
}
